gmp-backup:
  database:
    enabled: true
    path: /gmpcloud/data/pgdata
  base-shell-path: /Users/luyangqian/Desktop/test

spring:
  datasource:
    driver-class-name: org.h2.Driver
    # 这里每次服务启动就会加载schema和data的数据进行初始化
    schema: classpath:db/init-database.sql
    #data: classpath:db/init-data.sql
    #使用混合模式，默认情况下，H2 只运行一个进程访问，true 表示可以多个进程可以访问同一个数据库
    url: jdbc:h2:~/backup;AUTO_SERVER=TRUE;DB_CLOSE_DELAY=-1
    #url: jdbc:h2:file:/Users/luyangqian/Desktop/h2/backup
    username: root
    password: 123456
  h2:
    console:
      enabled: true
      path: /h2-console

mybatis:
  mapperLocations: classpath:mapper/*.xml
  type-aliases-package: com.leateck.gmp.backup.core.entity
  #type-handlers-package: com.leateck.gmp.backup.handler
  #日志打印
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

pagehelper:
  helperDialect: h2
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql