server:
  port: 8110

spring:
  application:
    name: gmp-backup
  messages:
    basename: il8n/messages
    encoding: utf-8
  profiles:
    active: dev
  thymeleaf:
    mode: LEGACYHTML5
    prefix: classpath:/templates/
    suffix: .html
    cache: false
#logging:
  #level:
    #root: debug
